### ISSUE TITLE
Thanks for the amazing code!

### ISSUE THREAD

**Issue by viggi1000** [oxullo/Arduino-MAX30100#1]
Hi, Thanks for the kickass work with MAX30100. 
Can you tell me what all pins must be connected apart from SDA,SCL and power? 

Will this code work with newer arduino like the Arduino Zero, MKR1000?

P.S: It looks like Ladyada from Adafruit is working on the MAX30100 module too (The code was incomplete though)

**Comment by oxullo** [comment]
Hey @viggi1000, sorry for the late answer.
Just wire up the sensor as suggested in the MAX30100's datasheet (page 8) and connect the I2C bus to your µC (remember the pullups, if your host doesn't have them). I haven't used the interrupt so no need for it to be connected.
I don't see any reason why it shouldn't work with the mkr, but I tested it only with the UNO r3.
Adafruit will release a breakout board sooner or later and I wonder if they'll be releasing driver and higher level calculation interfaces.
Feel free to contribute, if you will!

**Comment by oxullo** [comment]
@viggi1000 check the [schematic](extras/arduino-wiring.pdf)
