### ISSUE TITLE
Arduino+MAX30100(RCWL-0530) Unable to begin MAX30100

### ISSUE THREAD

**Issue by William-An** [oxullo/Arduino-MAX30100#13]
Hi, thank you for developing such code for MAX30100!

But as my title says, after connecting the sensor to arduino uno, the serial console shows nothing. However, after I unplugged the sensor from my breadboard, the serial console starts to print "Heart rate:0.00bpm / SpO2:0%." After I inserted some "Serial.println();" in  the MAX30100.cpp, I found out that the code stopped at this line: "Wire.write(data);" in "MAX30100::writeRegister" during the "MAX30100::begin" process. 

I really cannot solve, could you help me through this?

**Comment by William-An** [comment]
P.S. I cannot detect my MAX30100 through i2CScanner either... After I burnt the i2CScanner into my arduino, the serial console showed nothing, and the code seemed to stop. But after I unplugged the MAX(again), the console started to work

**Comment by William-An** [comment]
After checking my MAX30100 datasheet and its SDA & SCL pins' voltage, I realized that it must work under **3.3v of I2C** instead of the **5v on arduino**. I think that is the final reason behind this.

**Comment by mollyandchloe** [comment]
I used the rcwl-0530 module, to get it to work I had to cut the 1.8V to the pullup resistors and connect to 3.3V pull up.

Then I had to play with the LED current - Using 4.4 or 7.6 ma Worked well for me.

Thanks for this code, it works great.

**Comment by oxullo** [comment]
@William-An did you check this brief schematics? https://github.com/oxullo/Arduino-MAX30100/blob/master/extras/arduino-wiring.pdf

@mollyandchloe thanks for your contribution. Does it really work for you with such low bias current?

**Comment by ghostmanzero** [comment]
Hi everyone.i connected RCWL 0530 to arduino. I loaded the code. But it is not working. Rcwl is not working. I think normally red should be operating but as you can see it is not working. And when I open the serial port all I can see is "initializing MAX30100" . can anybody help me? 
![1490368532943-304003239](https://cloud.githubusercontent.com/assets/26488956/24297666/4108804a-10ac-11e7-9c35-cfd3d797fc2b.jpg)

**Comment by ghostmanzero** [comment]
Connections :
Vin => arduino 3. 3v 
Scl => ardunio Scl 
Sda=>ardunio sda
Int=> ardunio pin 2 
Gnd=> arduino gnd

**Comment by ghostmanzero** [comment]
After connecting the int to the 3.3v (without a pull resistor) now the red led is working. But I still cannot get any result.it doesn't detect the beat. It stops on "pox.begin() ;"  it looks like max30100 is not responding :/.  I have to RCWL. I tried both of them. Nothing changed . I don't know where my mistake is.  I followed the instructions. And I couldn't get a result. I need help

**Comment by ghostmanzero** [comment]
@mollyandchloe how did you change the led current?

**Comment by challee99** [comment]
use IIC to change RD/IRD current

**Comment by dokechin** [comment]
Please teach me.
Is it necessary to connect RD and IRD pins?
Where to connect Arduino pins Number separately?

**Comment by challee99** [comment]
OK， I can show you how to connect it . Just.. wait a moment...Get something to handle with..

**Comment by challee99** [comment]
I get a meetting...

**Comment by challee99** [comment]
![Uploading YG2V2V800KL4JG78$52N$@F.png…]()

**Comment by challee99** [comment]
when IR_LED+/R_LED+ is connected with 3.3V
The IRD/RD should be low or connect to GND. So the RedLED/IRLED can be lighten.

**Comment by dokechin** [comment]
Thank,you very much.
After connecting to GND,LED has changed shine stronger.

**Comment by JAICHANGPARK** [comment]
I resolved this problem that wasn't operated in arduino UNO. Arduino UNO doesn't have TWI register.
So. Connect 10k ohm register on sdk, scl pin. Then operate Try

**Comment by dokechin** [comment]
Thank,you. I tried 1.0KΩ。That going but cannot pick up beat constantly.
 I'will try value up the register.

**Comment by oxullo** [comment]
@JAICHANGPARK the Uno equips an ATMega328p which sports a hardware I2C/TWI interface.. And watch out for the pullup, 10k might be too high: with 4,7k I can already see the effects of an RC.
@dokechin check #14 for the beat issue you're experiencing

**Comment by sezarosama000** [comment]
hey can anyone show me the code plz, im thinking maybe mine misses something
@oxullo
@ghostmanzero 
@challee99

**Comment by sunny950** [comment]
hi everyone..i have connected max30100 rcw0530 to arduino i loaded the code but in serial monitor its just showing initializing max30100..nothing shows after it can anybody tell me how to fix it.. my pin connections are
Vin => arduino 5v
Scl => arduino analog a5
Sda=>arduino analog a4
Int=> ardunio digital pin 2
Gnd=> arduino gnd

**Comment by oxullo** [comment]
@sezarosama000 try the new example MAX30100_Tester on v1.1.0

**Comment by oxullo** [comment]
@sunny950 make sure you have proper pullups. Read the README.md and check the proposed schematics in the extras folder

**Comment by sunny950** [comment]
@oxullo thank u.i m trying without pullup resistors.should i use two pullup resistor for sda and scl pins seperatly..can u tell me where to connect these pullup ressistor i m new to this project

**Comment by dokechin** [comment]
@sunny950
RCW0530 I2C module voltage is 1.8V, so level converter is needed between Arduino and RCW0530. You should buy a voltage level converter board and try again.

**Comment by sunny950** [comment]
@dokechin brother in max30100 there is an inside voltage regulator..

**Comment by dokechin** [comment]
Please see the topic below, bidirectional level converter is needed.
https://forum.arduino.cc/index.php?topic=447071.0

**Comment by sunny950** [comment]
thank u i have tried mega 2560 and its working but its not calcuating sp02 while beat is detected and temperature also showing.what i have to do to calculate spo2.its either have value 0 or 100% which is incorrect i have connected my wires as follow
sda to arduino sda
scl to arduino scl
ird and red common ground with arduino grnd
gnd to arduino ground
![beat](https://cloud.githubusercontent.com/assets/27894764/25449717/0f4e8e84-2ad6-11e7-9479-60350ecb6c45.jpg)


 

![beat](https://cloud.githubusercontent.com/assets/27894764/25449358/fbf0d2b2-2ad4-11e7-9ec7-9372a6d1a58d.jpg)

**Comment by kamran-ali** [comment]
@sunny950 were u able to solve the problem.
and need some help when i am connecting ird and rd to common ground the red led does'nt blink,
but if i keep ird open the red is blinking. 
and on running test module the red=0 and ir=0.
and do i have to connect interrupt to any digital pin and if it has to be pulled up or down.

**Comment by kamran-ali** [comment]
i am using mega2560 so i dont need a pull up register for sda scl, but do i still need it for interrupt ? @oxullo

**Comment by MAX30100problem** [comment]
can anyone help me please?
I am trying to get the spo2 using max30100 and arduino nano. I have wired all the pins as an instructions. And the red LED started lighting. But we I am trying to run the code (tester or any of the codes) , i face with this error: Initializing max30100, Failed : I2C error 

to be noted that I wired scl, sdk , int via 4.7k pull up resisitors to vcc (5 volt).

**Comment by AhmadZMQ** [comment]
**@challee99** I did it as you said but the problem is both RED and IRLED doesn't light up.when I connect the one with GND (RED led alone) they got light up but  doesn't respond something. What we have to do for.kindly help plz.

**Comment by sunny950** [comment]
i have built a sensor for it having ir transmitter and ir reciever ..i
tried om max30100 but cant get any accurate value so i done it through
another method.

**Comment by liviuanc** [comment]
The same issue the red and it LEDs are not turning on

**Comment by liviuanc** [comment]
I'm using mega with  the same 4.7 k pull up rezistor

**Comment by challee99** [comment]
@AhmadZMQ  check your progarm. there is no problem with your LED.

**Comment by Dwight21** [comment]
can you give me the wiring for max30100 to arduino mega 2560?

**Comment by liviuanc** [comment]
From 5 volt I pulled up the i2c lines with 4.7k rezistors

**Comment by sunny950** [comment]
in arduino mega 2560 there are special pins for scl and sda so use that and
for red and ird i have already point the wirings ..

**Comment by sunny950** [comment]
use arduino mega 2560 instead ..dont have to use pull up resistors while
using arduino mega 2560

On 25 Nov 2017 19:35, "liviuanc" <notifications@github.com> wrote:

From 5 volt I pulled up the i2c lines with 4.7k rezistors

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/oxullo/Arduino-MAX30100/issues/13#issuecomment-346944130>,
or mute the thread

**Comment by Dwight21** [comment]
so the  wiring is this VIN->5V, SCL(PULLUP4.7K)->SDL,SDA(PULLUP4.7K)->SDA,IRD&RD->GND,GND->GND. i am right sir ?

**Comment by Dwight21** [comment]
can you give me the circuit of it guys . it shows FAILED

**Comment by Dwight21** [comment]
@sunny950  when you using your max30100 to arduino your wiring is this VIN->5V, SCL(PULLUP4.7K)->SDL,SDA(PULLUP4.7K)->SDA,IRD&RD->GND,GND->GND.

**Comment by 1bharath1** [comment]
I too had a problem where it was only printing 0 in all columns.

The fix for it is to just uncomment this line
pox.setIRLedCurrent(MAX30100_LED_CURR_17_4MA);

I came to know about this from

http://edycube.blog.fc2.com/blog-entry-982.html

**Comment by Shooting77** [comment]
@challee99 What's IIC ? and how I will use it??

**Comment by challee99** [comment]
@Shooting77   Its Communication bus. You should google it .

**Comment by AhmadZMQ** [comment]
Hi,
IIC bus is used to make or build a relation or connection between master
and slave to make connection communicable.It is a software based address
transmission.
If you're using one-to-one master slave communication then no need to
define the address of slave else you might be declare the address of all
slave which has to be communicate with master.You should have to use the
SDA and SCL pin to communicate for the same.To get the addess of the slave
you would have to visit their datasheet.

**Comment by AhmadZMQ** [comment]
Also you can go through this link https://www.i2c-bus.org/.

**Comment by Shooting77** [comment]
@AhmadZMQ thank you, but I connected SDA  & SCL  of MAX30100 to the  SDA(A4)  & SCL(A5) of the Arduino UNO but i still get the (Initializing pulse oximeter..) only without beats.

**Comment by AhmadZMQ** [comment]
Hi,
hunmmmmmmmmmmmmmmmm.yeah! I also tried hard to commnicate using the pins as
said by you but got no luck😖.I'm not sure this is the problem of
manufacturing or any other technical issues.I  suggest you a link to
puerchage the new one and get the fun--click o this lin khttps://
learn.sparkfun.com/tutorials/max30105-particle-and-pulse-ox-sensor-hookup-guide

**Comment by Shooting77** [comment]
@AhmadZMQ is this (max30105) working with Arduino such as it described in this site https://
learn.sparkfun.com/tutorials/max30105-particle-and-pulse-ox-sensor-hookup-guide

**Comment by AhmadZMQ** [comment]
yup....Arduino UNO,Mega, as well as Nano....

**Comment by Shooting77** [comment]
Thanks so much @AhmadZMQ

**Comment by AhmadZMQ** [comment]
It's my pleasure....have a fun with your electronics👍.

**Comment by dianjach** [comment]
I'm having problems. max30100 (rcwl0530) can not work. I'm using your library max30100. and run the max30100 tester and just show it

![wp_20180325_22_10_31_pro](https://user-images.githubusercontent.com/37766658/37883086-975488c6-30d2-11e8-9e1f-d412723a6200.jpg)
![wp_20180325_22_09_28_pro](https://user-images.githubusercontent.com/37766658/37883115-c19ee4c8-30d2-11e8-80b2-d8c90d8729ae.jpg)

pin max30100 vin = pin arduino v3,3
pin max30100 scl = pin arduino scl ( 4,7 R )
pin max30100 sda = pin arduino sda ( 4,7 R )
pin max30100 int = pin arduino d2 ( 4,7 R )
pin max30100 GND = pin arduino GND

this is like @mesutsaygioglu project.  but I do not understand
can some one help me??

**Comment by AhmadZMQ** [comment]
Hi,
Is this working for him( @mesutsaygioglu <https://github.com/mesutsaygioglu>
 ).Also , you can try out by open the INT pin.
As I already told you to just use max30105 (
https://learn.sparkfun.com/tutorials/max30105-particle-and-pulse-ox-sensor-hookup-guide)
breakout board for convenience.I don't know whats wrong with max30100
breakout board,I didn't find any solution for him at yet.

**Comment by dianjach** [comment]
i have problem sensor data. the sensor value jumps with a large range. how is the data sensor stable ?? anyone can help

**Comment by AhmadZMQ** [comment]
Firstly,just tell me which sensor are you using and let's explain little
bit of you problem....

**Comment by dianjach** [comment]
saya menggunakan max30100 rcwl0530.

**Comment by AhmadZMQ** [comment]
Hi,
Please purchase a new one MAX301005 from sparkfun.
I  suggest you a link to purchase the new one and get the fun--click o this
link - https://learn.sparkfun.com/tutorials/max30105-particle-
and-pulse-ox-sensor-hookup-guide

**Comment by Shooting77** [comment]
Is any one has a library of MPU6050 gyroscope of  for proteus 8??

**Comment by AhmadZMQ** [comment]
Hi,
u can go for this link..https://github.com/jarzebski/Arduino-MPU6050

**Comment by Shooting77** [comment]
I want the library gyroscope of for proteus 8 NOT for Arduino , Thanks @AhmadZMQ

**Comment by AhmadZMQ** [comment]
HI,
I apologise,what is proteus 8.I listen first  time can u tell me plz....🤔

**Comment by AhmadZMQ** [comment]
Hi,
I saw this,It's so cool s/w and provides a simulation.It's so interesting
too.
Can u let me know, what type of problem u encounter.As I understand that u
can use Arduino IDE to code and make compatible with Proteus by adding
Arduino library to the Proteus like this (click n c--
http://www.instructables.com/id/How-to-add-Arduino-Library-in-to-Proteus-7-8/)way
.
👍

**Comment by Saphal3** [comment]
Hi all, I was using MAX30102 and had the same issue. I solved the problem by using 1 pull-up resistor (4.7 kohm) for SDA pin and another one (4.7 kohm) for SCL pin. Vin was connected to 5V of Arduino and also both pull-up resistors were connected to 5V. I got these information from this link, http://mikrokontroler.pl/2017/09/14/przyklad-pulsoksymetr-max30100-plus-kamduino-uno/
Thanks,

**Comment by CarlaZeine** [comment]
@mesutsaygioglu @challee99 
**use IIC to change RD/IRD current
could you tell me how please ?

**Comment by MaBoy29** [comment]
Hi! When using the Tester code I get this error : Initializing MAX30100..FAILED: wrong part ID 0x15 (expected: 0x11).

Can you help me find my problem pleaze ?

**Comment by FelipeMdeO** [comment]
Check if you are using max30100 or max30102.

Em qua, 19 de jun de 2019 12:19 PM, MaBoy29 <notifications@github.com>
escreveu:

**Comment by MaBoy29** [comment]
@FelipeMdeO Which one should I use? (I have both)

**Comment by FelipeMdeO** [comment]
To this library, only max30100.

Em qua, 19 de jun de 2019 1:57 PM, MaBoy29 <notifications@github.com>
escreveu:

**Comment by MaBoy29** [comment]
@FelipeMdeO  I am using max30100 right now and I still have the same problem.

**Comment by FelipeMdeO** [comment]
Please, look again.

In datasheet of max30102 (https://datasheets.maximintegrated.com/en/ds/MAX30102.pdf )page 11 you have Part ID = 0x15
![image](https://user-images.githubusercontent.com/14298854/59810562-2c960380-92dc-11e9-8c34-c2181a3adff2.png)
But in max30100 (https://datasheets.maximintegrated.com/en/ds/MAX30100.pdf), Part ID is 0x11:
![image](https://user-images.githubusercontent.com/14298854/59810582-551dfd80-92dc-11e9-932e-b828bb8c5257.png)
So, you have max30102 in your board.
Please, if the problem continues, send photo of your wire.

**Comment by CarlaZeine** [comment]
Hi,

You should do some modifications on the Max30100 board to work with
arduino. That is because of the voltage 1.8v or 3v.

Please check the image below.

You should cut the connection between one rail of the voltage regulator and
the resistor, then you have to connect the resistors to Vin.

**Comment by FelipeMdeO** [comment]
Please, look again.

In datasheet of max30102 (
https://datasheets.maximintegrated.com/en/ds/MAX30102.pdf )page 11 you have
Part ID = 0x15
[image: image]
<https://user-images.githubusercontent.com/14298854/59810562-2c960380-92dc-11e9-8c34-c2181a3adff2.png>
But in max30100 (https://datasheets.maximintegrated.com/en/ds/MAX30100.pdf),
Part ID is 0x11:
[image: image]
<https://user-images.githubusercontent.com/14298854/59810582-551dfd80-92dc-11e9-932e-b828bb8c5257.png>
So, you have max30102 in your board.
Please, if the problem continues, send photo of your wire.

Em qui, 20 de jun de 2019 12:25 PM, CarlaZeine <notifications@github.com>
escreveu:

> Hi,
>
> You should do some modifications on the Max30100 board to work with
> arduino. That is because of the voltage 1.8v or 3v.
>
> Please check the image below.
>
> You should cut the connection between one rail of the voltage regulator and
> the resistor, then you have to connect the resistors to Vin.
>

**Comment by MaBoy29** [comment]
@FelipeMdeO I think you are right! It is marked as a Max30100 but it seems to respond as a Max30102... 

Do you know another library for that one ?

**Comment by FelipeMdeO** [comment]
Its because max30100 and 30102 have same pin out and foot print, so you can
change one per other in ae board.
U can use it:
https://learn.sparkfun.com/tutorials/max30105-particle-and-pulse-ox-sensor-hookup-guide/all

Em sex, 21 de jun de 2019 12:13 PM, MaBoy29 <notifications@github.com>
escreveu:

**Comment by sunitasonu** [comment]
#include <Wire.h>
#include "MAX30100_PulseOximeter.h"
 
#define REPORTING_PERIOD_MS     1000
 
// PulseOximeter is the higher level interface to the sensor
// it offers:
//  * beat detection reporting
//  * heart rate calculation
//  * SpO2 (oxidation level) calculation
PulseOximeter pox;
 
uint32_t tsLastReport = 0;
 
// Callback (registered below) fired when a pulse is detected
void onBeatDetected()
{
    Serial.println("Beat!");
}
 
void setup()
{
    Serial.begin(9600);
 
    Serial.print("Initializing pulse oximeter..");
 
    // Initialize the PulseOximeter instance
    // Failures are generally due to an improper I2C wiring, missing power supply
    // or wrong target chip
    if (!pox.begin()) {
        Serial.println("FAILED");
        for(;;);
    } else {
        Serial.println("SUCCESS");
    }
 
    // The default current for the IR LED is 50mA and it could be changed
    //   by uncommenting the following line. Check MAX30100_Registers.h for all the
    //   available options.
     pox.setIRLedCurrent(MAX30100_LED_CURR_7_6MA);
 
    // Register a callback for the beat detection
    pox.setOnBeatDetectedCallback(onBeatDetected);
}
 
void loop()
{
    // Make sure to call update as fast as possible
    pox.update();
 
    // Asynchronously dump heart rate and oxidation levels to the serial
    // For both, a value of 0 means "invalid"
    if (millis() - tsLastReport > REPORTING_PERIOD_MS) {
        Serial.print("Heart rate:");
        Serial.print(pox.getHeartRate());
        Serial.print("bpm / SpO2:");
        Serial.print(pox.getSpO2());
        Serial.println("%");

        tsLastReport = millis();
    }
}

hello sir this is my program when i am running this program only using max30100 sensor then it is working but if i call any other funtion in void loop it is not working i am not getting how to solve this trying from 15 days not getting answer even i searched so many articles but dint get the answer plz if anyone knows plz reply as soon as early thank you

**Comment by pahart2208** [comment]
Hi.  Yes, I've struggled with this for a few days.  Works fine as-is when writing to serial or LCD, but when I add anything, the output from MAX30100 stops.  In my case I was trying to write to my cloud services dashboard using WiFi.
I'm no s/w expert, but....Seems like the pox.update() has to run at a minimum 100Hz i.e. cycle time of <10ms.  I put a couple of software timers in the code and when the code above runs, it takes between 1 and 2 ms, which is easily fast enough.  However, the Wifi write was taking around 350ms and so pox.update() stopped working properly.  
Now I understand the comment in the code:
// Make sure to call update as fast as possible
At least 100 times each second, or it won't work!
So, your other function must be taking longer than 10ms which stops pox.update() working.
Still trying to figure out a workaround.  
Hope that helps - or at least gives some insight into the problem.

**Comment by Kalsara01** [comment]
so I've been struggling with this for some time and finally able to get it working. 
I ordered got 2 "MAX30100" boards but 2 are not alike. 
![20200623_072248](https://user-images.githubusercontent.com/64644736/85352329-4f787a80-b523-11ea-9e8e-512a475dca34.jpg)
turns out 1st one is MAX30100 and the 2nd one is MAX30102
so kept the max30102 aside and started working on max30100. I used an Arduino Mega. 
Vin to 3.3v, GND to GND, SCL to SCL, SDA to SDA and INT to digital pin 2. 
then I scanned for i2c devices
**File > examples > Wire > i2c _scanner** 
No devices detected. 
then I broke the connection between SMD resistors and voltage regulator and solder a wire to those resistors ( check red circle in the picture) and connected that wire to 5V 
then again did an I2C device scan. -> device at address 57! 
then upload the max30100 debug file and it worked! 
then tried again the max30100 tester ---> "could not convert 'sensor.MAX30100::begin((pulseWidth)3, (ledCurrent)14, (sampleRate)1)' from 'void' to 'bool'" 
Sketch->include libraray -> MAX30100lib 
and finally got everything to work !!!

**Comment by simtcrom** [comment]
> so I've been struggling with this for some time and finally able to get it working.
> I ordered got 2 "MAX30100" boards but 2 are not alike.
> ![20200623_072248](https://user-images.githubusercontent.com/64644736/85352329-4f787a80-b523-11ea-9e8e-512a475dca34.jpg)
> turns out 1st one is MAX30100 and the 2nd one is MAX30102
> so kept the max30102 aside and started working on max30100. I used an Arduino Mega.
> Vin to 3.3v, GND to GND, SCL to SCL, SDA to SDA and INT to digital pin 2.
> then I scanned for i2c devices
> **File > examples > Wire > i2c _scanner**
> No devices detected.
> then I broke the connection between SMD resistors and voltage regulator and solder a wire to those resistors ( check red circle in the picture) and connected that wire to 5V
> then again did an I2C device scan. -> device at address 57!
> then upload the max30100 debug file and it worked!
> then tried again the max30100 tester ---> "could not convert 'sensor.MAX30100::begin((pulseWidth)3, (ledCurrent)14, (sampleRate)1)' from 'void' to 'bool'"
> Sketch->include libraray -> MAX30100lib
> and finally got everything to work !!!

I have got MAX30102 green.
I already removed all three resistors.

VIN to 3.3V
GND to GND
INT to D0
SCL to D1
SDA to D2
using 4.7K pullup resistors (connected to 3.3V) in SCL, SDA.

Ran Example -> i2cdetect -> i2cdetect and I can see its detected in 57

Ran Example MAX30100lib -> MAX30100_Debug getting error

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld
Failed to initialize the HRM sensor
ERROR: Failed to initialize pulse oximeter

Can any one help me please?

**Comment by simtcrom** [comment]
> Check if you are using max30100 or max30102.

I too get 
Initializing MAX30100..FAILED: wrong part ID 0x15 (expected: 0x11
I am using MAX30102 green. Can you provide a working program please?
