### ISSUE TITLE
any workaround for raspberry pi 3

### ISSUE THREAD

**Issue by madhujiot** [oxullo/Arduino-MAX30100#15]
hi, I could get the desired results in arduino. Further, any leads/idea on raspberry pi 3 to hook on getting the pulse-oxy and HB values with python code? thanks.

**Comment by oxullo** [comment]
The current implementation of the driver is a bit naive and pretty time-critical, nevertheless it could be a starting point to integrate a port. The chip supports FIFO reads, which you could use to overcome linux kernel's jitter.
More on the matter would be a bit out of scope! You can still interface an arduino to the Pi..
