### ISSUE TITLE
Arduino-MAX30100

### ISSUE THREAD

**Issue by SIH-HUA** [oxullo/Arduino-MAX30100#17]
hi~
nice to meet  you.
i want to ask you some question about Arduino-MAX30100.
when I used your file ,I found there was no  file Wire.h.
do you have this question?

**Comment by oxullo** [comment]
@SIH-HUA your description is quite vague.. which file you're referring to? in which environment you've been trying to build it? versions (environment and library)?

**Comment by oxullo** [comment]
Please reopen if you're still experiencing the issue
