### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by lavr2016** [oxullo/Arduino-MAX30100#2]
Hello, Oxullo!
Thanks for Your great Job!
Can You help me to translate a filter functions (from MAX30100_Filters.h) from CPP to C? I try to use Your project for another platform. 
Best regards, Oleg

**Comment by oxullo** [comment]
Hey @lavr2016, thanks!
It's pretty straightforward: convert the classes into two .c/.h by moving the member variables to static global vars and adding an init and step function. You can also avoid the global vars by keeping a register on the caller's side ("v" for the LPF and "dcw" for the DC remover).
Good luck!
