### ISSUE TITLE
I2c error in tester

### ISSUE THREAD

**Issue by nghiatruong1204** [oxullo/Arduino-MAX30100#22]
@oxullo  this library is really heplful, tks bro :)))
can u teach me how to fix I2c error found by MAX30100_tester pls  :))

**Comment by oxullo** [comment]
@nghiatruong1204 which error? :) Post it here and please add all the details you can, including: which breakout and arduino you're using, which arduino framework/version, how did you connect the breakout.
Check thoroughly the readme, it holds some relevant info to perform an initial self check. Usually the main issue is the lack of proper pullups on the SDA/SCL lines.

**Comment by nghiatruong1204** [comment]
@oxullo 
here is my arduino nano and max30100, i use arduino arduino IDE 1.8.1

**Comment by nghiatruong1204** [comment]
@oxullo 
this is how i connect my breakout 
VIN connected to 1.8v (converted from 3.3v )
SCL to A5 and SDA to A4 (yellow and orange wires)
INT to D2 
SCL SDA and INT are equipped with pullups (4.7k ohm resistors)
IRD to 3.3v and RD to GND (3.3v power is provided by arduino nano)
GND to common GND by arduino nano
I will give you more in detail by pictures of my breakout :)))

**Comment by oxullo** [comment]
@nghiatruong1204 to which rail the pullups are connected to?

**Comment by nghiatruong1204** [comment]
@oxullo hope this gonna be helpful xDDD  
![pullupscl_sda_2](https://cloud.githubusercontent.com/assets/28290911/25954373/4c33f710-3690-11e7-8bad-ba9f03127b58.png)

**Comment by nghiatruong1204** [comment]
i think there is no problem with the sensor, only I2C error :((
![picture1](https://cloud.githubusercontent.com/assets/28290911/25978215/cc6b5902-3675-11e7-9fbb-f51a5112ef96.png)

**Comment by nghiatruong1204** [comment]
I2C error solved but _**heart rate**_ and **_SP02_** go wrong :) 
do u have any solution for this ? i need this done for school project xDDD

![picture2](https://cloud.githubusercontent.com/assets/28290911/25998619/ba98b196-36d6-11e7-965c-59977c62382a.jpg)
![picture1](https://cloud.githubusercontent.com/assets/28290911/25998625/c043f3e4-36d6-11e7-8a1d-b048e66f9415.jpg)

**Comment by oxullo** [comment]
How did you solve the primary issue? please leave it described it here for the community!
Regarding the readout, check the new hints I added to https://github.com/oxullo/Arduino-MAX30100/blob/master/README.md (last paragraph).

**Comment by nghiatruong1204** [comment]
i changed all the wires and different breadboard bro :)
then i used the power provided by arduino nano for VIN, result in the brighter IR led 
still working on readouts xDDD

**Comment by oxullo** [comment]
Glad that you found out. Good luck with experimenting the bias current, that might be tricky!

**Comment by nghiatruong1204** [comment]
[tester IR and Rd result.txt](https://github.com/oxullo/Arduino-MAX30100/files/999742/tester.IR.and.Rd.result.txt)
what can these data tell about the sensor?

**Comment by x3bachi** [comment]
Same problem here, I get 0 reading for heart rate and SpO2.
please help

**Comment by nghiatruong1204** [comment]
@x3bachi  since i unplugged IRD it works perfectly 
u just need to wire from RD to GND and follow wiring instruction form this library :))))

**Comment by x3bachi** [comment]
Thank you @nghiatruong1204 you replied fast :)
it works now but the reading is weird some times reads high values and sometimes reads low values also it skips some beats

**Comment by x3bachi** [comment]
Also the sensor keeps​ getting hot to the point i can't touch it

**Comment by AsmaaSayed** [comment]
Hi @x3bachi
I have the same with MAX30100 that it's reads are non logical 
Can you help me if you solved it in the past

**Comment by x3bachi** [comment]
Hi Asmaa,
It's been a long time since I worked with this sensor, but I
remember fixing it.
the schematics that came with it were wrong if you follow it some of the
pins will be short-circuited.
If you have many sensors try playing with changing the pins and hopefully
none of them will burn xD.
Good luck with your project :).

**Comment by AsmaaSayed** [comment]
Ok
Thanks very much for your help
