### ISSUE TITLE
I2C error

### ISSUE THREAD

**Issue by MAX30100problem** [oxullo/Arduino-MAX30100#25]
can anyone help me please?
I am trying to get the spo2 using max30100 and arduino nano. I have wired all the pins as an instructions. And the red LED started lighting. But we I am trying to run the code (tester or any of the codes) , i face with this error: Initializing max30100, Failed : I2C error

to be noted that I wired scl, sdk , int via 4.7k pull up resisitors to vcc (5 volt).

**Comment by oxullo** [comment]
I consider this ticket as invalid, since it's missing all the relevant information required for the report. Please feel free to reopen but make sure you fill in the details shown in the issue text.
