### ISSUE TITLE
could not convert 'sensor.MAX30100::begin((pulseWidth)3u, (ledCurrent)14u, (sampleRate)1u)' from 'void' to 'bool'

### ISSUE THREAD

**Issue by rench94** [oxullo/Arduino-MAX30100#31]
Hi oxullo, i download your code n run on the arduino uno and it pop out the error something like this which is could not convert 'sensor.MAX30100::begin((pulseWidth)3u, (ledCurrent)14u, (sampleRate)1u)' from 'void' to 'bool'. Can u teach me how to solve this?

**Comment by oxullo** [comment]
Please open an issue using the provided template and a complete code snippet
