### ISSUE TITLE
Initializing pulse oximeter..FAILED in my serial port my wiring to UNO is this VIN=>V5, SCL(pullup4.7k)=>SCL, SDA(pullup4.7k)=>SDA, 

### ISSUE THREAD

**Issue by Dwight21** [oxullo/Arduino-MAX30100#34]
### Troubleshooting checklist

- [x] I read the README (on master) thoroughly
- [x] I ran the MAX30100_Tester and I'm going to paste the output down below
- [x] I filled in all the details of my setup down below

### Details of my setup

* Arduino hardware:
* MAX30100 breakout:
* Arduino framework version:
* MAX30100 library version:

**Comment by oxullo** [comment]
Please take time to add all the required information requested in the issue template and add a schematic capture of your wiring on a new ticket
