### ISSUE TITLE
i will ask if this result is right 

### ISSUE THREAD

**Issue by eduard88806815** [oxullo/Arduino-MAX30100#36]
### Troubleshooting checklist

- [ ] I read the README (on master) thoroughly
- [ ] I ran the MAX30100_Tester and I'm going to paste the output down below
- [ ] I filled in all the details of my setup down below

### Details of my setup

* Arduino hardware:mega 2560
* MAX30100 breakout:connection VIN=>5V,SCL and SDA(with4.7k resistor)=>SCLandSDA, GND=>GND
* Arduino framework version:
* MAX30100 library version:

![image](https://user-images.githubusercontent.com/23523220/33362782-c89797c2-d518-11e7-8b01-374156ab0aa6.png)

**Comment by oxullo** [comment]
Have you tried https://github.com/oxullo/Arduino-MAX30100#sketchy-beat-frequency-readouts ?

**Comment by oxullo** [comment]
Closing the issue due to inactivity
