### ISSUE TITLE
error could not convert from 'void' to 'bool'

### ISSUE THREAD

**Issue by HNeumeier** [oxullo/Arduino-MAX30100#38]
I get this compalition Error can you help me.
error: could not convert 'sensor.MAX30100::begin((pulseWidth)3u, (ledCurrent)14u, (sampleRate)1u)' from 'void' to 'bool'

**Comment by ghost** [comment]
How to solve this problem ?

**Comment by kentpaul** [comment]
hello did you solve this problem?

**Comment by ghost** [comment]
> hello did you solve this problem?

Go to Sketch -> Include Library -> MAX30100lib

**Comment by HNeumeier** [comment]
Sorry it's a long time ago I don't know how I solved it, maybe I downloaded another library.

**Comment by tinkerinoyt** [comment]
plz help !
