### ISSUE TITLE
Error on compile!

### ISSUE THREAD

**Issue by Boubis** [oxullo/Arduino-MAX30100#45]
hello! Every example i try to compile i always get this error about a specific header file!
i have all the libraries and header files neccesery in the same folder as the .ino file.
![screenshot_1](https://user-images.githubusercontent.com/37153597/37106794-60dced2e-223b-11e8-9f78-d92d5c2b5a0c.png)

Can you help me?

**Comment by oxullo** [comment]
Please submit a proper issue report indicating all the required info

**Comment by Boubis** [comment]
i cant understand a more simple way to explain it!
when i try to compile MAX30100_Minimal example there is a compile error!
here is the exact error message:
![image](https://user-images.githubusercontent.com/37153597/37180383-7e2007bc-2331-11e8-892b-a1a6ad155242.png)

i have all the nessecery header files and libraries in the same folder 
![image](https://user-images.githubusercontent.com/37153597/37180435-a364a370-2331-11e8-8339-a283672b5da0.png)

![image](https://user-images.githubusercontent.com/37153597/37180473-d3dfbddc-2331-11e8-8f31-e0ee98f2b266.png)

i hope i make myself more inambiguous! Your help is very valuable

**Comment by oxullo** [comment]
When you create an issue, there's a default text on the body of the issue that requires you to fill in the details of the environment and circumstances. I can help if you help me first.

**Comment by Boubis** [comment]
sorry i am new to github and i dont know! you have to answer only to this format that you use? or "unofficially" you can make an exception and answer here? If you cant i understand and i will create an issue properly
