### ISSUE TITLE
IOT MAX30100

### ISSUE THREAD

**Issue by 12awan** [oxullo/Arduino-MAX30100#47]
I tried to use the code MAX30100_Minimal and added it to connect to ThingSpeak, an IoT platform. I added the same line of code that I used for the previous i2c sensor to send data to Thingspeak, but somehow when I added it to the code MAX30100, the serial monitor started displaying the value 0 for the tick for percentage of SpO2 not reading, but when use MAX30100_Tester why not can upload in arduino and nodemcu, please help

**Comment by oxullo** [comment]
When filing an issue, fill in ALL the required fields and questions indicated in the template.
For each test case provide a snippet of the error, source code, comments
