### ISSUE TITLE
Max30100 working problem

### ISSUE THREAD

**Issue by ahmedbashar** [oxullo/Arduino-MAX30100#50]
Hi, I have a problem with max30100 working, it is working only with 5v, but it is not working with 3.3v..what is the problem, please??

**Comment by oxullo** [comment]
MAX30100 works with a max Vdd of 2.0V, typically 1.8V. Every other voltage rail (eg: LED power DRV/LED, I2C lines pullups and INT) accept typically 3.3V, max 5V. I can confirm that it works with 3.3V I2C bus signalling. If you need further help, read the README and eventually open a ticket answering all the questions in the ticket template.
