### ISSUE TITLE
Failed to initialize HRM sensor  

### ISSUE THREAD

**Issue by azlinasuerman** [oxullo/Arduino-MAX30100#53]
![image](https://user-images.githubusercontent.com/37065484/38632944-c9f88176-3df0-11e8-8b15-44016a251725.png)

Hi i'm having this problem and i don't know how to troubleshoot it. Can anyone help me ? Thank You

**Comment by oxullo** [comment]
It's most likely that you're not using a MAX30100 but another newer HRM. This library works only with the (now outdated) MAX30100.
Make sure you also read the README thoroughly and next time please use the issue template to report your issue!
