### ISSUE TITLE
Max30100 with Thingspeak

### ISSUE THREAD

**Issue by Marinamyat24** [oxullo/Arduino-MAX30100#54]
### Troubleshooting checklist

- [OK ] I read the README (on master) thoroughly
- [OK ] I ran the MAX30100_Tester and I'm going to paste the output down below
- [OK ] I filled in all the details of my setup down below

### Description of the issue
I am using Max30100 and the sensor reads the data correctly and bpm and spo2 values are correct  before uploading to thingspeak. After uploading to thingspeak, bpm and spo2 values only show "0".

### Output from MAX30100_Tester example
![image](https://user-images.githubusercontent.com/40665735/42417871-fae18004-82b9-11e8-908d-6630d6745cce.png)

### Details of my setup
The wiring is as below:
MAX30100   --->   Arduino
     VIN                       5V
     SCL                      A5 with 4.7k ohm pullup resistor 
     SDA                     A4 with 4.7k ohm pullup resistor         
     INT                      3.3V
    GND                     GND
       

* Arduino hardware:   Arduino UNO
* MAX30100 breakout:  RCWL-0530
* Arduino framework version:  Arduino 1.8.5  
* MAX30100 library version:   MAX30100lib 1.2.1

**Comment by pabloesya** [comment]
do you have some progress..... cause I'm in the same problem :'c

**Comment by oxullo** [comment]
Please check #52
