### ISSUE TITLE
Getting a rolling graph

### ISSUE THREAD

**Issue by sdmiller42** [oxullo/Arduino-MAX30100#8]
First off awesome work best code I have seen out there. My issue is trying to get a rolling graph so how could I go about that?

**Comment by sdmiller42** [comment]
You can also email me at sam.miller59@gmail.com to talk more about it.

**Comment by sdmiller42** [comment]
Like I am not sure how to put the debug in conjuction of the rolling_graph. I think that is my issue to get  crisp signal.

**Comment by oxullo** [comment]
Hey @sdmiller42 but can I imply that you get a varying signal? Any explicit error?
The MAX30100_Debug example uses a very basic communication protocol to update the rolling_graph app. What do you see if you connect to the arduino's serial port with a terminal emulator?

**Comment by oxullo** [comment]
@sdmiller42 feel free to reopen if you're still experiencing issues. Please add any note regarding how you found your way thru otherwise!
